/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SpaceGrid {
        "flex": string;
        "gap": 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;
        "row": boolean;
    }
}
declare global {
    interface HTMLSpaceGridElement extends Components.SpaceGrid, HTMLStencilElement {
    }
    var HTMLSpaceGridElement: {
        prototype: HTMLSpaceGridElement;
        new (): HTMLSpaceGridElement;
    };
    interface HTMLElementTagNameMap {
        "space-grid": HTMLSpaceGridElement;
    }
}
declare namespace LocalJSX {
    interface SpaceGrid {
        "flex"?: string;
        "gap"?: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;
        "row"?: boolean;
    }
    interface IntrinsicElements {
        "space-grid": SpaceGrid;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "space-grid": LocalJSX.SpaceGrid & JSXBase.HTMLAttributes<HTMLSpaceGridElement>;
        }
    }
}
